apiVersion: v1
kind: Service
metadata:
  name: cast_service
  namespace: {{.Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-cast-service
  ports:
      - protocol: {{ .Values.cast-service.service.protocol }}
        port: {{ .Values.cast-service.service.port }}
        targetPort: {{ .Values.cast-service.service.targetPort }}
  type: {{ .Values.cast-service.service.type }}
