apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie_service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-service
    spec:
      containers:
          - name: {{ .Release.Name }}-movie-service-container
            image: {{ .Values.movie_service.deployment.repository }}
            imagePullPolicy: IfNotPresent
            command: [ "sh", "-c", "uvicorn app.main:app --reload --host 0.0.0.0 --port 8000" ]
            ports:
              - containerPort: {{ .Values.movie-service.deployment.containerPort }}
            env:
              - name: DATABASE_URI
                value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
              - name: CAST_SERVICE_HOST_URL
                value: http://cast_service:8000/api/v1/casts/
