apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: {{.Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  ports:
      - protocol: {{ .Values.nginx.service.protocol }}
        port: {{ .Values.nginx.service.port }}
        targetPort: {{ .Values.nginx.service.targetPort }}
  type: {{ .Values.nginx.service.type }}
