apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{.Release.namespace }}-movie-db-pv
spec:
  storageClassName: default
  capacity:
    storage: {{ .Values.movie_db.pv.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.movie_db.pv.hostPath }}
