apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-movie-db-secret
type: Opaque
data:
  movie-db-username: {{.Values.movie_db.secret.username}}
  movie-db-password: {{.Values.movie_db.secret.password}}
  movie-db-database: {{.Values.movie_db.secret.database}}