apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-{{.Values.namespace }}-cast-db-pv
spec:
  storageClassName: default
  capacity:
    storage: {{ .Values.cast_db.pv.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.cast_db.pv.hostPath }}
