apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-cast-db-secret
  namespace: {{.Values.namespace }}
type: Opaque
data:
  cast-db-username: {{.Values.cast_db.secret.username}}
  cast-db-password: {{.Values.cast_db.secret.password}}
  cast-db-database: {{.Values.cast_db.secret.database}}