apiVersion: v1
kind: Service
metadata:
  name: cast-db
  namespace: {{.Values.namespace }}
spec:
  selector:
    app: {{ .Release.Name }}-cast-db
  ports:
    - protocol: {{ .Values.cast_db.service.protocol }}
      port: {{ .Values.cast_db.service.port }}
      targetPort: {{ .Values.cast_db.service.targetPort }}
